### ISSUE TITLE
Add a creative Error 404 page (HTML & CSS required only)

### ISSUE THREAD

**Issue by Rishabh04-02** [Rishabh04-02/Elective-manager#18]
This project uses Google material design light [CSS](http://getmdl.io/).
Create a creative, stylsh Error 404 page.
The file for 404 page is [here](https://github.com/Rishabh04-02/Elective-manager/blob/master/views/public/public_404.php) you need to edit only this file.
Your content goes in between line [16](https://github.com/Rishabh04-02/Elective-manager/blob/master/views/public/public_404.php#L16) to line [40](https://github.com/Rishabh04-02/Elective-manager/blob/master/views/public/public_404.php#L40)

**Comment by samthom** [comment]
Can I work on this.

**Comment by Rishabh04-02** [comment]
@samthom  sure you can 👍.
