### ISSUE TITLE
Update project link in the following files

### ISSUE THREAD

**Issue by Rishabh04-02** [Rishabh04-02/Elective-manager#19]
Update this link ``https://github.com/Rishabh04-02/Elective-manager-new`` to ``https://github.com/Rishabh04-02/Elective-manager`` in the following files
1. ``views/public/public_bugs.php`` on line [2](https://github.com/Rishabh04-02/Elective-manager/blob/master/views/public/public_bugs.php#L2)
2. ``README.md`` on line 2 and line 35
3. ``views/public/public_about.php`` on line [37](https://github.com/Rishabh04-02/Elective-manager/blob/master/views/public/public_about.php#L37)
4. ``views/public/public_contact.php`` on line [37](https://github.com/Rishabh04-02/Elective-manager/blob/master/views/public/public_contact.php#L37)
5. ``views/public/public_credits.php`` on line [37](https://github.com/Rishabh04-02/Elective-manager/blob/master/views/public/public_credits.php#L37)
6. ``views/includes/includes_footer.php`` on line [13](https://github.com/Rishabh04-02/Elective-manager/blob/master/views/includes/includes_footer.php#L13)

**Comment by psr1919plus21** [comment]
I would like to work on this.

**Comment by Rishabh04-02** [comment]
@psr1919plus21 Thanks for showing your interest in the issue, but I already got a PR for it.
