### ISSUE TITLE
Update Project name in the following files

### ISSUE THREAD

**Issue by Rishabh04-02** [Rishabh04-02/Elective-manager#21]
Please update the text from ``Elective-manager-new`` to ``Elective-manager`` in the following files
1. ``views/public/public_404.php``
2. ``views/public/public_about.php``
3. ``views/public/public_contact.php``
4. ``views/public/public_credits.php``
5. ``README.md``
You can find the line numbers which you need to update from [here](https://github.com/Rishabh04-02/Elective-manager/search?utf8=%E2%9C%93&q=Elective-manager-new)

**Comment by andela-iadeniyi** [comment]
@Rishabh04-02 I'll work on this.

**Comment by Rishabh04-02** [comment]
@andela-iadeniyi Thanks for showing your interest in the issue, but I already got a PR for the issue.

**Comment by andela-iadeniyi** [comment]
Alright
